'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("JWLibrary_MediaInserter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend ReadOnly Property buttonDelete() As String
            Get
                Return ResourceManager.GetString("buttonDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export JWPUB.
        '''</summary>
        Friend ReadOnly Property buttonExport() As String
            Get
                Return ResourceManager.GetString("buttonExport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insert.
        '''</summary>
        Friend ReadOnly Property buttonInsert() As String
            Get
                Return ResourceManager.GetString("buttonInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore publication.
        '''</summary>
        Friend ReadOnly Property buttonRestore() As String
            Get
                Return ResourceManager.GetString("buttonRestore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select medias to insert.
        '''</summary>
        Friend ReadOnly Property buttonSelect() As String
            Get
                Return ResourceManager.GetString("buttonSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show all publications.
        '''</summary>
        Friend ReadOnly Property checkShowAll() As String
            Get
                Return ResourceManager.GetString("checkShowAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Week from.
        '''</summary>
        Friend ReadOnly Property dateStringFrom() As String
            Get
                Return ResourceManager.GetString("dateStringFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to to.
        '''</summary>
        Friend ReadOnly Property dateStringTo() As String
            Get
                Return ResourceManager.GetString("dateStringTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Images or videos.
        '''</summary>
        Friend ReadOnly Property dialogFiler() As String
            Get
                Return ResourceManager.GetString("dialogFiler", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Collection not found.
        '''</summary>
        Friend ReadOnly Property errorCollection404() As String
            Get
                Return ResourceManager.GetString("errorCollection404", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close JW Library to continue.
        '''</summary>
        Friend ReadOnly Property errorJWL() As String
            Get
                Return ResourceManager.GetString("errorJWL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to restore publication, please try again later.
        '''</summary>
        Friend ReadOnly Property errorRestoreGeneric() As String
            Get
                Return ResourceManager.GetString("errorRestoreGeneric", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Advanced.
        '''</summary>
        Friend ReadOnly Property groupAdvanced() As String
            Get
                Return ResourceManager.GetString("groupAdvanced", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Publication.
        '''</summary>
        Friend ReadOnly Property groupPub() As String
            Get
                Return ResourceManager.GetString("groupPub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Ico() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
